from typing import Any, List, Tuple


Bodypoints_t = List[float]
"""
A list of 33 bodypoints obtained from Mediapipe.
"""

Robot_Angles_t = List[float]
"""
A list of angles for the robot's joints.
"""


Color_Frame_t = Any
"""
Video frame as a numpy array.
"""

Depth_Frame_t = Any
"""
PyRealsense frame of depth data; use .get_distance(x_coord, y_coord) to read distance data out of it.
"""

Frame_Pair_t = Tuple[Color_Frame_t, Depth_Frame_t]
"""
Pair of Color & Depth Frames generated by publish_frame
"""

ts_Robot_Angles_t = Tuple[int, Robot_Angles_t]
"""
Tuple of (timestamp, Robot_Angles_t)
"""
ts_Frame_Pair_t = Tuple[int, Frame_Pair_t]
"""
Tuple of (timestamp, Frame_Pair_t)
"""
ts_Bodypoints_t = Tuple[int, Bodypoints_t]
"""
Tuple of (timestamp, Bodypoints_t)
"""

q_Robot_Angles_t = List[ts_Robot_Angles_t]
"""
Queue type for timestamped Robot_Angles_t
"""
q_Frame_Pair_t = List[ts_Frame_Pair_t]
"""
Queue type for timestamped Frame_Pair_t
"""
q_Bodypoints_t = List[ts_Bodypoints_t]
"""
Queue type for timestamped Bodypoints_t
"""

