import numpy.typing as nptyping
from typing import Any
from util import PoseLandmarkerResult, mpImage
from model import RobotAngles_t, Bodypoints_t

Color_Frame_t = nptyping.NDArray
"""
Video frame as a numpy array.
"""

Depth_Frame_t = Any
"""
PyRealsense frame of depth data; use .get_distance(x_coord, y_coord) to read distance data out of it.
"""

Frame_Pair_t = tuple[Color_Frame_t, Depth_Frame_t]
"""
Pair of Color & Depth Frames generated by publish_frame
"""

ts_RobotAngles_t = tuple[int, RobotAngles_t]
ts_Frame_Pair_t = tuple[int, Frame_Pair_t]
ts_Bodypoints_t = tuple[int, Bodypoints_t]

q_Robot_Angles_t = list[ts_RobotAngles_t]
q_Frame_Pair_t = list[ts_Frame_Pair_t]
q_Bodypoints_t = list[ts_Bodypoints_t]
