// Generated by gencpp from file custom_msg/arm.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_ARM_H
#define CUSTOM_MSG_MESSAGE_ARM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msg
{
template <class ContainerAllocator>
struct arm_
{
  typedef arm_<ContainerAllocator> Type;

  arm_()
    : header()
    , shoulder()
    , elbow()
    , wrist()  {
      shoulder.assign(0.0);

      elbow.assign(0.0);

      wrist.assign(0.0);
  }
  arm_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , shoulder()
    , elbow()
    , wrist()  {
  (void)_alloc;
      shoulder.assign(0.0);

      elbow.assign(0.0);

      wrist.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _shoulder_type;
  _shoulder_type shoulder;

   typedef boost::array<float, 3>  _elbow_type;
  _elbow_type elbow;

   typedef boost::array<float, 3>  _wrist_type;
  _wrist_type wrist;





  typedef boost::shared_ptr< ::custom_msg::arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::arm_<ContainerAllocator> const> ConstPtr;

}; // struct arm_

typedef ::custom_msg::arm_<std::allocator<void> > arm;

typedef boost::shared_ptr< ::custom_msg::arm > armPtr;
typedef boost::shared_ptr< ::custom_msg::arm const> armConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::arm_<ContainerAllocator1> & lhs, const ::custom_msg::arm_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.shoulder == rhs.shoulder &&
    lhs.elbow == rhs.elbow &&
    lhs.wrist == rhs.wrist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::arm_<ContainerAllocator1> & lhs, const ::custom_msg::arm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg::arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::arm_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::arm_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f17acee9610e62286ac9052ebccb36dc";
  }

  static const char* value(const ::custom_msg::arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf17acee9610e6228ULL;
  static const uint64_t static_value2 = 0x6ac9052ebccb36dcULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/arm";
  }

  static const char* value(const ::custom_msg::arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32[3] shoulder\n"
"float32[3] elbow\n"
"float32[3] wrist\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msg::arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.shoulder);
      stream.next(m.elbow);
      stream.next(m.wrist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::arm_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "shoulder[]" << std::endl;
    for (size_t i = 0; i < v.shoulder.size(); ++i)
    {
      s << indent << "  shoulder[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.shoulder[i]);
    }
    s << indent << "elbow[]" << std::endl;
    for (size_t i = 0; i < v.elbow.size(); ++i)
    {
      s << indent << "  elbow[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.elbow[i]);
    }
    s << indent << "wrist[]" << std::endl;
    for (size_t i = 0; i < v.wrist.size(); ++i)
    {
      s << indent << "  wrist[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.wrist[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_ARM_H
