stages:
  - build

# Define variables
variables:
  ROS_DISTRO: noetic                     # Specify the ROS distribution
  CATKIN_WS: $CI_PROJECT_DIR/ros_ws      # Define the path for the Catkin workspace (Updated)

# Use an official ROS Docker image
image: ros:${ROS_DISTRO}-robot

# --- Build Stage ---
# Job to build the Catkin workspace.
catkin_build:
  stage: build
  before_script:
    # Install essential build tools and dependencies
    - apt-get update -qq
    - apt-get install -y -qq --no-install-recommends \
        git \
        python3-pip \
        python3-catkin-tools \
        python3-rosdep \
        build-essential
    # Install Python package dependencies
    - pip3 install --upgrade pip
    - pip3 install mujoco numpy matplotlib # Add other pip dependencies if needed
    # Initialize rosdep
    - rosdep init || echo "rosdep already initialized."
    - rosdep update
    # Source the ROS environment
    - source /opt/ros/${ROS_DISTRO}/setup.bash
  script:
    # Create Catkin Workspace structure
    - echo "Creating Catkin workspace at ${CATKIN_WS}..."
    - mkdir -p ${CATKIN_WS}/src
    # Copy repository content to workspace src
    - echo "Copying repository contents to workspace..."
    - cp -r ./* ${CATKIN_WS}/src/
    # Navigate into the workspace
    - cd ${CATKIN_WS}
    # Install ROS dependencies from package.xml files
    # Ensure custom_msg package is present in src/
    - echo "Installing ROS dependencies using rosdep..."
    - rosdep install --from-paths src --ignore-src -r -y --rosdistro ${ROS_DISTRO} \
        || echo "WARNING: Some rosdep dependencies failed to install. Continuing build..."
    # Build the Catkin workspace
    - echo "Building Catkin workspace..."
    - catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release
  artifacts:
    # Keep build artifacts for debugging
    paths:
      - ${CATKIN_WS}/logs/
      - ${CATKIN_WS}/devel/
      - ${CATKIN_WS}/build/
    expire_in: 1 week
  allow_failure: false # Fail pipeline on build error