controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
initial:  # Define initial robot poses per group
  - group: right_arm
    pose: home
  - group: left_arm
    pose: home