right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_shoulder_pitch_joint
    - right_shoulder_roll_joint
    - right_shoulder_yaw_joint
    - right_elbow_joint
  gains:
    right_shoulder_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_shoulder_pitch_joint
    - left_shoulder_roll_joint
    - left_shoulder_yaw_joint
    - left_elbow_joint
  gains:
    left_shoulder_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1